### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: datasets/flowcharts/flowcharts768_val.record; No such file or directory

### ISSUE THREAD

**Issue by viral98** [mlcv-ime/faster-rcnn-graphics#3]
Upon executing
`python3 tf-models/research/object_detection/eval.py --pipeline_config_path=models/flowcharts/inceptionv2/pipeline.config --checkpoint_dir=models/flowcharts/inceptionv2/trained --eval_dir=models/flowcharts/inceptionv2/eval --gpudev=-1 --run_once=True
`
I get the following error
`INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:depth of additional conv before box predictor: 0
WARNING:tensorflow:From /home/viral/Code/Python/MachineLearning/faster-rcnn-graphics/tf-models/research/object_detection/core/box_predictor.py:380: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2018-10-08 21:56:47.414693: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Restoring parameters from models/flowcharts/inceptionv2/trained/model.ckpt-25000
INFO:tensorflow:Restoring parameters from models/flowcharts/inceptionv2/trained/model.ckpt-25000
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>, datasets/flowcharts/flowcharts768_val.record; No such file or directory
	 [[Node: parallel_read/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>, datasets/flowcharts/flowcharts768_val.record; No such file or directory
	 [[Node: parallel_read/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]
WARNING:root:The following classes have no ground truth examples: [1 2 3 4 5 6 7]
/home/viral/Code/Python/MachineLearning/faster-rcnn-graphics/tf-models/research/object_detection/utils/metrics.py:144: RuntimeWarning: invalid value encountered in true_divide
  num_images_correctly_detected_per_class / num_gt_imgs_per_class)
/home/viral/Code/Python/MachineLearning/faster-rcnn-graphics/tf-models/research/object_detection/utils/object_detection_evaluation.py:612: RuntimeWarning: Mean of empty slice
  mean_ap = np.nanmean(self.average_precision_per_class)
/home/viral/Code/Python/MachineLearning/faster-rcnn-graphics/tf-models/research/object_detection/utils/object_detection_evaluation.py:613: RuntimeWarning: Mean of empty slice
  mean_corloc = np.nanmean(self.corloc_per_class)
Traceback (most recent call last):
  File "tf-models/research/object_detection/eval.py", line 158, in <module>
    tf.app.run()
  File "/home/viral/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tf-models/research/object_detection/eval.py", line 145, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir)
  File "/home/viral/Code/Python/MachineLearning/faster-rcnn-graphics/tf-models/research/object_detection/evaluator.py", line 210, in evaluate
    save_graph_dir=(eval_dir if eval_config.save_graph else ''))
  File "/home/viral/Code/Python/MachineLearning/faster-rcnn-graphics/tf-models/research/object_detection/eval_util.py", line 381, in repeated_checkpoint_run
    save_graph_dir)
  File "/home/viral/Code/Python/MachineLearning/faster-rcnn-graphics/tf-models/research/object_detection/eval_util.py", line 286, in _run_checkpoint_once
    global_step = tf.train.global_step(sess, tf.train.get_global_step())
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/viral/.local/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/queues.py", line 70, in QueueRunners
    coord.join(threads, stop_grace_period_secs=120)
  File "/home/viral/.local/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/viral/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/viral/.local/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/home/viral/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1205, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/viral/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: datasets/flowcharts/flowcharts768_val.record; No such file or directory
	 [[Node: parallel_read/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]
`

**Comment by eyagarci** [comment]
@viral98 can you explain to me how you can solve this problem
