### ISSUE TITLE
Cannot import name 'string_int_label_map_pb2'

### ISSUE THREAD

**Issue by hackerghost93** [mlcv-ime/faster-rcnn-graphics#4]
When I try to run your project it seems i get this what is wrong with it?
By the way I can't find this file in object_detections.protos 
``
Traceback (most recent call last):
  File "tf-models/research/object_detection/eval.py", line 56, in <module>
    from object_detection import evaluator
  File "/home/hackerghost/flowchat/faster-rcnn-graphics/tf-models/research/object_detection/evaluator.py", line 24, in <module>
    from object_detection import eval_util
  File "/home/hackerghost/flowchat/faster-rcnn-graphics/tf-models/research/object_detection/eval_util.py", line 27, in <module>
    from object_detection.utils import label_map_util
  File "/home/hackerghost/flowchat/faster-rcnn-graphics/tf-models/research/object_detection/utils/label_map_util.py", line 22, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'
``

**Comment by soumitraghosh388** [comment]
Hi @hackerghost93 Please go through https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md which deals with the installation part.
More appropriately you need to execute this -

```
# From tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.
```
It will create all protos files.
